config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  resources :sessions, only: [ :create ] do
    get 'destroy', to: 'sessions#destroy', on: :collection, as: :destroy
    get 'authenticate', to: 'sessions#authenticate', on: :member
  end

  resources :topics, only: [ :index, :new, :create, :show, :edit, :update, :destroy ] do
    post 'add_teacher', on: :member
    post 'remove_teacher', on: :member
    post 'add_student', on: :member
    post 'remove_student', on: :member
    
    resources :comments, only: [ :index, :create, :destroy ]
  end

  resources :users, only: [ :show, :update, :edit ]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  skip_before_action :verify_authenticity_token, if: :json_request?

  before_filter :authenticate_user

  helper_method :current_user
  helper_method :current_user?

  helper_method :topic_json

  def current_user
    if session[:user_id]
      @current_user = User.find(session[:user_id]) if @current_user.nil?
    end
    @current_user
  end

  def current_user?(user)
    return !user.nil? && current_user == user
  end

  def user_json(user)
    user.as_json.merge({
      gravatar_url: gravatar_url(user.email, size=50),
      routes: {
        show: user_path(user)
      }
    })
  end

  def comment_json(topic, comment)
    comment.as_json.merge(
      author: user_json(comment.author),
      isAuthor: current_user?(comment.author),
      routes: {
        destroy: topic_comment_path(topic, comment)
      }
    )
  end

  def topic_json(topic)
    topic.as_json.merge({
      owner: user_json(topic.owner),
      isTeaching: topic.teachers.include?(current_user),
      isLearning: topic.students.include?(current_user),
      member_count: topic.members.size,
      teachers: topic.teachers.sort_by(&:display_name).map { |u| user_json(u) },
      students: topic.students.sort_by(&:display_name).map { |u| user_json(u) },
      comments: topic.comments.sort_by(&:created_at).reverse.map { |c| comment_json(topic, c) },
      routes: {
        show: topic_path(topic),
        teach: add_teacher_topic_path(topic), 
        stopTeaching: remove_teacher_topic_path(topic),
        learn: add_student_topic_path(topic), 
        stopLearning: remove_student_topic_path(topic),
        comments: topic_comments_path(topic)
      }
    })
  end

  protected

  def json_request?
    request.format.json?
  end

  def authenticate_user
    if current_user.nil?
      flash[:danger] = 'Please log in'
      redirect_to(:root)
    end
  end

  def gravatar_url(email_address, size=80)
    "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(email_address.strip.downcase)}?s=#{size}&d=mm"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  GRAVATAR_PATH = 'http://www.gravatar.com/avatar'

  def gravatar_url(email_address, size=80)
    "#{GRAVATAR_PATH}/#{Digest::MD5.hexdigest(email_address.strip.downcase)}?s=#{size}&d=mm"
  end

  def gravatar_for(user, size=80)
    avatar = content_tag(:a, href: user_path(user)) do
      image_tag(gravatar_url(user.email, size), alt: user.display_name, title: user.display_name) 
    end
    avatar.html_safe
  end

  def user_email_domain
    Rails.application.config.user_email_domain
  end
end

app/views/application/_auth.html.haml
.auth
  .navbar-right
    - if current_user
      .navbar-text
        Welcome, 
        = link_to "#{current_user.display_name}!", user_path(current_user)
      .navbar-text
        %span Not #{current_user.display_name}?
        = link_to "Get a new sign in email", destroy_sessions_path, class: 'secondary'
    - else
      = form_tag(sessions_path, class: 'navbar-form') do
        .form-group
          = label_tag('Send a sign in link to')
          = email_field_tag(:email, nil, class: 'form-control', placeholder: "me@#{Rails.application.config.user_email_domain}")
        %button.btn.btn-default{type: 'submit'} Go!

app/views/application/_flash_messages.html.haml
-flash.each do |msg_type, msg|
  -case msg_type.to_sym
  -when :success
    -type = 'alert-success'
  -when :error, :danger
    -type = 'alert-danger'
  -when :warn, :warning
    -type = 'alert-warning'
  -else
    -type = 'alert-info'

  .alert.alert-dismissable{ class: type }
    %button.close{:type => 'button', 'data-dismiss' => 'alert', 'aria-label' => 'Close'}
      %span{'aria-hidden' => 'true'}
        &times
    = msg

app/views/application/_footer.html.haml
-if Rails.application.config.google_analytics_id
  %script#analytics
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ="ga('create', '#{Rails.application.config.google_analytics_id}', 'auto');"
    ga('send', 'pageview');

app/views/application/_name_missing.html.haml
- if current_user and not current_user.name
  .alert.alert-warning.text-center
    .strong You haven't set your name!
    
    = form_for current_user, url: user_path(current_user), html: { method: "patch", class: 'form-inline' } do |form|
      .form-group
        = form.label(:name, 'My name is')
        = form.text_field(:name, class: 'form-control')
      %button.btn.btn-default{type: 'submit'} Update

app/views/application/_navbar.html.haml
%nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      %a.navbar-brand{href: (url_for :root) }
        =image_tag 'logo.png', alt: 'SoClassy Logo', class: 'navbar-logo'
    = render 'auth'

app/views/application/_topics.html.haml
- if @topics.empty?
  %p.text-muted No topics to display
- else
  - topics.each do |topic|
    .row
      .col-xs-12
        .pull-right
          =react_component('QuickJoin', { collectionName: 'Teacher', initialMemberCount: topic.teachers.size, isInitiallyMember: (topic.teachers.include? current_user), joinUrl: add_teacher_topic_path(topic), leaveUrl: remove_teacher_topic_path(topic) }, { tag: 'span' })
          =react_component('QuickJoin', { collectionName: 'Student', initialMemberCount: topic.students.size, isInitiallyMember: (topic.students.include? current_user), joinUrl: add_student_topic_path(topic), leaveUrl: remove_student_topic_path(topic) }, { tag: 'span' })
          
        %span.h4
          %a{href: topic_path(topic)}=topic.name
          %small
            -if topic.owner
              by
              %a.hidden-link{href: user_path(topic.owner)}= topic.owner.display_name
        %hr